name: "example_model_triton"
platform: "tensorflow_savedmodel"
max_batch_size: 4
input [
  {
    name: "input_0"
    data_type: TYPE_FP32
    dims: [ 4 ]
  }
]
output [
  {
    name: "output_0"
    data_type: TYPE_FP32
    dims: [ 3 ]
  }
]
